//@version=6
strategy("CROSS", initial_capital = 10000, calc_on_every_tick = true, default_qty_type = strategy.percent_of_equity, default_qty_value = 100, dynamic_requests = true, overlay=true)

// 定义回测时间段
start_date = input.time(timestamp("1 Feb 2018 00:00 +0800"), "Date", group = "时间")
end_date = input.time(timestamp("31 Dec 2099 00:00 +0800"), "Date", group = "时间")
signalSymbol = input.symbol("SPX", "信号标的", group = "时间")

// 定义MA
ma_length = input.int(120, title = "均线")
long_ma_length = input.int(120, title = "牛熊均线")
long_ma_bool = input.bool(false, title = "长均线定牛熊")
above_long_ma_bool = input.bool(true, title = "长均线向上时抢跑")
ma_option = input.string(title="均线类型", defval="SMA", options=["EMA", "SMA", "RMA"])
compound = input.bool(true, title = "余额复利")
quantity = input.float(1.0, title = "固定数量")
ndx = "NDX"
spx = "SPX"
btc = "BTC"
dxy = "DXY"
no = ""
compare = input.string(title="相对强势", defval=no, options=[spx, ndx, dxy, btc, no], group = "相对")
ratio = input.float(1000.0, title="价格乘数", group = "相对")
ma_offset = input.float(15.0, title="均线偏离%", group = "均线偏离") / 100
ma_offset_close = input.bool(false, title="均线偏离平仓", group = "均线偏离")
signalClose = request.security(signalSymbol, timeframe.period, close)
signalHigh = request.security(signalSymbol, timeframe.period, high)
ma_value = ma_option == "SMA" ? ta.sma(signalClose, ma_length) : (ma_option == "EMA" ? ta.ema(signalClose, ma_length) : ta.rma(signalClose, ma_length))
long_ma_value = ma_option == "SMA" ? ta.sma(signalClose, long_ma_length) : (ma_option == "EMA" ? ta.ema(signalClose, long_ma_length) : ta.rma(signalClose, long_ma_length))

bool above_long_ma = true
if long_ma_bool
    above_long_ma := (not above_long_ma_bool and signalClose > long_ma_value) or (above_long_ma_bool and (long_ma_value > long_ma_value[1] and long_ma_value[1] > long_ma_value[2]) or signalClose > long_ma_value)

bool above_compare = true
float div_val = na
float div_ma_value = na
// 获取其他品种的收盘价格
if compare != no
    above_compare := false
    compare_symbol_close = request.security(compare, "D", close)
    div_val := signalClose * ratio / compare_symbol_close
    div_ma_value := ma_option == "SMA" ? ta.sma(div_val, ma_length) : (ma_option == "EMA" ? ta.ema(div_val, ma_length) : ta.rma(div_val, ma_length))
    if div_val >= div_ma_value
        above_compare := true

// 定义买入和卖出条件
buy_condition = above_long_ma and above_compare and signalClose > ma_value * 1.01
sell_condition = signalClose < ma_value * 0.99 or (ma_offset_close and signalHigh > ma_value * (1 + ma_offset))

// 检查当前时间是否在回测时间段内
in_date_range = (time >= start_date) and (time <= end_date)

// 执行买入操作
if (in_date_range and buy_condition)
    // 固定数量
    qty = quantity
    strategy.entry(id = "Buy", direction = strategy.long, comment = "Buy")

// 执行卖出操作
if sell_condition
    strategy.close("Buy", comment = "Sell")

// 绘制MA
plot(ma_value, title="MA", linewidth = 2, color=color.blue)
plot(long_ma_bool ? long_ma_value : na, title="LONG MA", linewidth = 2, color=color.gray)
plot(div_ma_value, title = "COMPARE_MA", display = display.status_line, color = color.orange)
plot(div_val, title = "COMPARE_VAL", display = display.status_line, color = color.orange)
